openapi: 3.0.0
servers: [ ]
info:
  version: "0.0.1"
  title: battleship-api
  description: TODO FILL THIS
paths:
  /system_info:
    get:
      tags:
        - Misc
      description: returns
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:

components:
  schemas:
    ServerInfo:
      type: object
      properties:
        version:
          type: string
          example: '0.4.3'
        authors:
          type: array

    Author:
      type: object
      properties:

